document:
  name: Linee guida su acquisizione e riuso di software per le pubbliche amministrazioni
  description:
      Linee guida in attuazione degli obblighi previsti dagli articoli 68 e 69 del Codice dell’Amministrazione Digitale in materia di acquisizione di software, valutazione comparativa, rilascio in open source, riuso.
  tags:
    - open source
    - linee guida
    - gdl opensource
    - riuso
